# Generated by Django 3.2.25 on 2026-03-20 01:04

import django.core.validators
from django.db import migrations, models
import rnd_platform.utils


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omimage',
            name='image',
            field=models.ImageField(upload_to=rnd_platform.utils.get_om_image_path, validators=[rnd_platform.utils.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='omrawdata',
            name='file',
            field=models.FileField(upload_to=rnd_platform.utils.get_om_raw_data_path, validators=[rnd_platform.utils.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'pdf', 'jpg', 'jpeg', 'png', 'txt'])]),
        ),
    ]
