# Generated by Django 3.2.25 on 2026-03-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0003_auto_20260320_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omimage',
            old_name='material',
            new_name='om',
        ),
        migrations.RenameField(
            model_name='omrawdata',
            old_name='material',
            new_name='om',
        ),
        migrations.AddField(
            model_name='organicmaterial',
            name='cost_per_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicmaterial',
            name='is_commercial',
            field=models.BooleanField(default=False),
        ),
    ]
