# Generated by Django 3.2.25 on 2026-03-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_materialimage_materialrawdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSlotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mm', 'Metal Material'), ('om', 'Organic Material')], max_length=20, unique=True)),
                ('slot_1_name', models.CharField(blank=True, help_text='Search Name for Slot 1 (e.g. Density)', max_length=50)),
                ('slot_2_name', models.CharField(blank=True, help_text='Search Name for Slot 2', max_length=50)),
                ('slot_3_name', models.CharField(blank=True, help_text='Search Name for Slot 3', max_length=50)),
                ('slot_4_name', models.CharField(blank=True, help_text='Search Name for Slot 4', max_length=50)),
                ('slot_5_name', models.CharField(blank=True, help_text='Search Name for Slot 5', max_length=50)),
            ],
        ),
    ]
