# Generated by Django 3.2.25 on 2026-03-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_searchslotconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cost_per_kg',
            field=models.FloatField(blank=True, help_text='Estimated cost in USD per kg', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_commercial',
            field=models.BooleanField(default=False, help_text='Is this material commercially available?'),
        ),
    ]
