# Generated by Django 3.2.25 on 2026-03-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0002_auto_20260320_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalmaterial',
            name='num_attr_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metalmaterial',
            name='num_attr_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metalmaterial',
            name='num_attr_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metalmaterial',
            name='num_attr_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metalmaterial',
            name='num_attr_5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
