# Generated by Django 3.2.25 on 2026-02-21 12:18

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('conditions', jsonfield.fields.JSONField(blank=True, default=dict, help_text='Store custom mixing conditions, temperatures, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormulationIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_or_amount', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='formulations.formulation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
        ),
    ]
