# Generated by Django 3.2.25 on 2026-03-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='memo',
            field=models.TextField(blank=True, default='', help_text='Mixing instructions, SOP, or general notes'),
        ),

        migrations.AlterField(
            model_name='formulation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
