# Generated by Django 3.2.25 on 2026-03-20 06:51

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0002_auto_20260320_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='manufacture_date',
            field=models.CharField(blank=True, default='', help_text='YY-MM-DD format', max_length=8),
        ),
        migrations.AlterField(
            model_name='formulation',
            name='conditions',
            field=jsonfield.fields.JSONField(blank=True, default=dict, help_text='Mixing conditions like RPM, Temp, etc.'),
        ),
    ]
